// Copyright 2026 Vas and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"

	"github.com/mvanhorn/printing-press-library/library/productivity/zapier/internal/cliutil"
	"github.com/mvanhorn/printing-press-library/library/productivity/zapier/internal/config"
	"github.com/spf13/cobra"
)

const zapierLoginURL = "https://zapier.com/app/login"

var launchBrowser = openBrowser

func openBrowser(url string) error {
	var name string
	var args []string
	switch runtime.GOOS {
	case "darwin":
		name, args = "open", []string{url}
	case "windows":
		name, args = "rundll32", []string{"url.dll,FileProtocolHandler", url}
	default:
		name, args = "xdg-open", []string{url}
	}
	return exec.Command(name, args...).Start() // #nosec G204 -- fixed opener and trusted constant URL.
}

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "auth",
		Short:       "Manage authentication for Zapier",
		Annotations: map[string]string{"pp:parent-group": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthSetTokenCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints concrete steps for getting a credential. Side-effect
// rule: print by default, --launch opt-in to open the URL, short-circuit when
// the verifier is running this in a sandboxed subprocess.
func newAuthSetupCmd(_ *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print browser-session cookie setup steps (use --launch to open Zapier login)",
		Example: "  zapier-pp-cli auth setup\n  zapier-pp-cli auth setup --launch",
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintf(w, "1. Sign in to Zapier at %s.\n", zapierLoginURL)
			fmt.Fprintln(w, "2. In your browser's developer tools, copy the complete Cookie request-header value from an authenticated Zapier request.")
			fmt.Fprintln(w, "   Treat it as a password: do not paste it into chat, logs, or commands that print it.")
			fmt.Fprintln(w, "3. Save it to the local credentials store using the commands for your shell:")
			fmt.Fprintln(w, "   macOS/Linux (hidden prompt):")
			fmt.Fprintln(w, "     printf 'Paste Zapier session cookie: ' >&2; IFS= read -rs ZAPIER_SESSION_COOKIE; printf '\\n' >&2")
			fmt.Fprintf(w, "     printf '%%s' \"$ZAPIER_SESSION_COOKIE\" | zapier-pp-cli auth set-token\n")
			fmt.Fprintln(w, "     unset ZAPIER_SESSION_COOKIE")
			fmt.Fprintln(w, "   Windows PowerShell (temporary access-restricted file):")
			fmt.Fprintln(w, "     Get-Content -Raw .\\private-cookie-file | zapier-pp-cli auth set-token")
			fmt.Fprintln(w, "     Remove-Item .\\private-cookie-file")
			if !launch {
				return nil
			}
			if cliutil.IsAnyHarness() {
				fmt.Fprintln(cmd.ErrOrStderr(), "verification harness: browser launch skipped")
				return nil
			}
			if err := launchBrowser(zapierLoginURL); err != nil {
				return fmt.Errorf("opening Zapier login: %w", err)
			}
			fmt.Fprintln(cmd.ErrOrStderr(), "opened Zapier login in your default browser")
			return nil
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the setup URL in your default browser")
	return cmd
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  zapier-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			refusals := cfg.CredentialRefusalSummaries()
			credentialRefused := len(refusals) > 0
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if credentialRefused {
					out["credential_refused"] = true
					out["credential_refusals"] = refusals
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed && credentialRefused {
					return authErr(cfg.CredentialRefusalError())
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed && credentialRefused {
				fmt.Fprintln(w, red("Credentials present but refused"))
				for _, refusal := range refusals {
					fmt.Fprintf(w, "  %s\n", refusal)
				}
				return authErr(cfg.CredentialRefusalError())
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Run 'zapier-pp-cli auth setup' for safe session-cookie instructions.")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func newAuthSetTokenCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:   "set-token",
		Short: "Save a Zapier session cookie to the credentials file",
		Long: "Save a Zapier browser-session cookie to the credentials file.\n\n" +
			"The cookie is read from stdin so it never appears in process arguments or shell history.",
		Example: "  printf '%s' \"$ZAPIER_SESSION_COOKIE\" | zapier-pp-cli auth set-token\n  zapier-pp-cli auth set-token < cookie-file",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			token, err := readSecretFromStdin(cmd.InOrStdin())
			if err != nil {
				return authErr(err)
			}

			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			// Clear any legacy auth_header so AuthHeader() falls through to
			// the newly-saved credential. Without this, a pre-existing
			// auth_header value (common after regenerate) shadows the saved
			// token and set-token silently has no effect. Silent clear (no
			// log line): a masked-tail variant could leak token bytes through
			// scripted dogfood that captures stderr.
			cfg.AuthHeaderVal = ""
			// Cookie auth: AuthHeader() reads the env-var-derived field, not
			// AccessToken. Writing the cookie to AccessToken via SaveTokens
			// would persist the bytes but leave doctor reporting "not
			// configured" — the slot the header builder consults stays empty.
			if err := cfg.SaveCredential(token); err != nil {
				return configErr(fmt.Errorf("saving token: %w", err))
			}

			savePath := credentialSavePath(cfg)
			// JSON envelope: {saved, config_path, credentials_path}.
			if flags.asJSON {
				out := map[string]any{
					"saved":       true,
					"config_path": cfg.Path,
				}
				if !cfg.AgentcookieManagedByExternalStore() {
					out["credentials_path"] = savePath
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Session cookie saved to %s\n", savePath)
			return nil
		},
	}
}

func credentialSavePath(cfg *config.Config) string {
	if cfg != nil && cfg.AgentcookieManagedByExternalStore() {
		return cfg.Path
	}
	if path, err := cliutil.CredentialsFilePath(); err == nil {
		return path
	}
	if cfg != nil {
		return cfg.Path
	}
	return ""
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  zapier-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("ZAPIER_SESSION_COOKIE") != "" {
				envStillSet = "ZAPIER_SESSION_COOKIE"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
