// Copyright 2026 Vas and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"os"

	"github.com/mvanhorn/printing-press-library/library/productivity/zapier/internal/cliutil"
	"github.com/mvanhorn/printing-press-library/library/productivity/zapier/internal/config"
	"github.com/spf13/cobra"
)

const zapierLoginURL = "https://zapier.com/app/login"

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "auth",
		Short:       "Manage authentication for Zapier",
		Annotations: map[string]string{"pp:parent-group": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthBrowserCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd prints the browser-auth steps. --launch starts the same
// private, cookie-safe flow as `auth browser`; it never opens an unrelated
// default-browser session that the CLI cannot capture.
func newAuthSetupCmd(flags *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Print automatic browser-session setup steps (use --launch to start)",
		Example: "  zapier-pp-cli auth setup\n  zapier-pp-cli auth setup --launch",
		Args:    cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			w := cmd.OutOrStdout()
			fmt.Fprintln(w, "1. Run 'zapier-pp-cli auth browser' on the computer you want to connect.")
			fmt.Fprintln(w, "2. The CLI downloads pinned Vercel Labs agent-browser, plus Chrome for Testing only if Chrome is missing.")
			fmt.Fprintf(w, "3. A dedicated private browser window opens %s.\n", zapierLoginURL)
			fmt.Fprintln(w, "4. Sign in normally. The CLI saves only Zapier cookies; it never prints or asks you to paste them.")
			fmt.Fprintln(w, "5. The CLI closes its sign-in window. Run only 'zapier-pp-cli session --agent --no-learn' to identify the connected account, then stop for confirmation.")
			if !launch {
				return nil
			}
			browser := newAuthBrowserCmd(flags)
			return browser.RunE(cmd, nil)
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Start the private browser sign-in flow")
	return cmd
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  zapier-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			refusals := cfg.CredentialRefusalSummaries()
			credentialRefused := len(refusals) > 0
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if credentialRefused {
					out["credential_refused"] = true
					out["credential_refusals"] = refusals
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed && credentialRefused {
					return authErr(cfg.CredentialRefusalError())
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed && credentialRefused {
				fmt.Fprintln(w, red("Credentials present but refused"))
				for _, refusal := range refusals {
					fmt.Fprintf(w, "  %s\n", refusal)
				}
				return authErr(cfg.CredentialRefusalError())
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Run 'zapier-pp-cli auth browser' to connect in a visible browser window.")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

func credentialSavePath(cfg *config.Config) string {
	if cfg != nil && cfg.AgentcookieManagedByExternalStore() {
		return cfg.Path
	}
	if path, err := cliutil.CredentialsFilePath(); err == nil {
		return path
	}
	if cfg != nil {
		return cfg.Path
	}
	return ""
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  zapier-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}
			if err := clearManagedAgentBrowserProfile(); err != nil {
				return configErr(fmt.Errorf("clearing the managed browser profile: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("ZAPIER_SESSION_COOKIE") != "" {
				envStillSet = "ZAPIER_SESSION_COOKIE"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials and managed browser profile cleared.")
			return nil
		},
	}
}
