// Copyright 2026 Vas and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DeliverSink describes where command output should be routed when
// --deliver is set. Parsed from the sink specifier "scheme:target".
type DeliverSink struct {
	Scheme string
	Target string
}

// ParseDeliverSink parses a --deliver value. Supported schemes:
//
//	stdout          -> default, no redirection
//	file:<path>     -> write output atomically to <path>
//
// Returns an error for unknown schemes with a message naming the
// supported set, so agents see a structured refusal rather than a
// silent misroute.
func ParseDeliverSink(spec string) (DeliverSink, error) {
	if spec == "" || spec == "stdout" {
		return DeliverSink{Scheme: "stdout"}, nil
	}
	idx := strings.Index(spec, ":")
	if idx == -1 {
		return DeliverSink{}, fmt.Errorf("unknown --deliver sink %q: expected scheme:target (supported: stdout, file:<path>)", spec)
	}
	scheme := spec[:idx]
	target := spec[idx+1:]
	switch scheme {
	case "file":
		if target == "" {
			return DeliverSink{}, fmt.Errorf("--deliver file:<path> requires a path")
		}
	default:
		return DeliverSink{}, fmt.Errorf("unknown --deliver scheme %q (supported: stdout, file)", scheme)
	}
	return DeliverSink{Scheme: scheme, Target: target}, nil
}

// Deliver routes a captured output buffer to the configured sink. stdout
// is a no-op because the buffer has already been streamed to stdout via
// the MultiWriter set up in root.go.
func Deliver(sink DeliverSink, body []byte, _ bool) error {
	switch sink.Scheme {
	case "", "stdout":
		return nil
	case "file":
		return deliverFile(sink.Target, body)
	case "webhook":
		return fmt.Errorf("remote webhook delivery is disabled: this product permits no remote writes")
	default:
		return fmt.Errorf("unsupported deliver sink %q", sink.Scheme)
	}
}

func deliverFile(path string, body []byte) error {
	// Atomic write: tmp + rename. Protects agents from seeing a partial
	// file if the process is interrupted mid-write.
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("creating deliver dir: %w", err)
		}
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o600); err != nil {
		return fmt.Errorf("writing deliver tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("replacing deliver file: %w", err)
	}
	return nil
}
