// Copyright 2026 Vas and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mvanhorn/printing-press-library/library/productivity/zapier/internal/cliutil"
	"github.com/spf13/cobra"
)

// FeedbackEntry is one line in the local feedback ledger. This product never
// sends feedback remotely because its remote boundary is strictly read-only.
type FeedbackEntry struct {
	Text      string    `json:"text"`
	CLI       string    `json:"cli"`
	Version   string    `json:"version"`
	AgentID   string    `json:"agent_id,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

const feedbackMaxTextLen = 4096

func feedbackFilePath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("creating feedback data dir: %w", err)
	}
	return filepath.Join(dir, "feedback.jsonl"), nil
}

// FeedbackEndpointConfigured is retained for agent-context compatibility.
// Remote feedback is permanently disabled for this read-only product.
func FeedbackEndpointConfigured() bool {
	return false
}

func appendFeedback(entry FeedbackEntry) error {
	p, err := feedbackFilePath()
	if err != nil {
		return err
	}
	f, err := os.OpenFile(p, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if err != nil {
		return fmt.Errorf("opening feedback ledger: %w", err)
	}
	defer f.Close()
	return json.NewEncoder(f).Encode(entry)
}

func newFeedbackCmd(flags *rootFlags) *cobra.Command {
	var useStdin bool
	cmd := &cobra.Command{
		Use:   "feedback [text]",
		Short: "Record feedback locally about this CLI",
		Long: `Feedback is captured only in the CLI data directory's feedback.jsonl.
It is never sent to a remote endpoint. Write what surprised you or tripped you
up so a maintainer with access to this machine can review it.`,
		Example: `  zapier-pp-cli feedback "the --since flag is inclusive but docs say exclusive"
  zapier-pp-cli feedback --stdin < notes.txt
  zapier-pp-cli feedback list --limit 10`,
		Annotations: map[string]string{"mcp:local-write": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			var text string
			if useStdin {
				data, err := io.ReadAll(cmd.InOrStdin())
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				text = strings.TrimSpace(string(data))
			} else if len(args) > 0 {
				text = strings.Join(args, " ")
			}
			text = strings.TrimSpace(text)
			if text == "" {
				return fmt.Errorf("feedback text is empty (pass arguments or --stdin)")
			}
			truncated := false
			if len(text) > feedbackMaxTextLen {
				text = text[:feedbackMaxTextLen]
				truncated = true
			}

			entry := FeedbackEntry{
				Text:      text,
				CLI:       "zapier-pp-cli",
				Version:   version,
				AgentID:   os.Getenv("AGENT_ID"),
				Timestamp: time.Now().UTC(),
			}
			if err := appendFeedback(entry); err != nil {
				return err
			}

			if flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"recorded":  true,
					"truncated": truncated,
					"remote":    "disabled",
					"entry":     entry,
				}, flags)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "feedback recorded locally (%d chars%s)\n", len(text), func() string {
				if truncated {
					return ", truncated"
				}
				return ""
			}())
			return nil
		},
	}
	cmd.Flags().BoolVar(&useStdin, "stdin", false, "Read feedback body from stdin rather than arguments")

	cmd.AddCommand(newFeedbackListCmd(flags))
	return cmd
}

func newFeedbackListCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List recent feedback entries",
		Annotations: map[string]string{
			"mcp:read-only": "true",
		},
		Example: `  zapier-pp-cli feedback list
  zapier-pp-cli feedback list --limit 5
  zapier-pp-cli feedback list --json`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			p, err := feedbackFilePath()
			if err != nil {
				return err
			}
			data, err := os.ReadFile(p)
			if err != nil {
				if os.IsNotExist(err) {
					if flags.asJSON {
						return printJSONFiltered(cmd.OutOrStdout(), []FeedbackEntry{}, flags)
					}
					return nil
				}
				return err
			}
			var entries []FeedbackEntry
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if line == "" {
					continue
				}
				var e FeedbackEntry
				if err := json.Unmarshal([]byte(line), &e); err != nil {
					continue
				}
				entries = append(entries, e)
			}
			if limit > 0 && limit < len(entries) {
				entries = entries[len(entries)-limit:]
			}
			return printJSONFiltered(cmd.OutOrStdout(), entries, flags)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 20, "Maximum number of recent entries to return")
	return cmd
}
