// Copyright 2026 Vas and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cliutil

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAtomicWritePrivateFileRefusesUnsafeEmptyTempBeforeWriting(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "credentials.toml")
	const oldContents = "access_token = \"old-token\"\n"
	const newContents = "access_token = \"new-token\"\n"
	if err := os.WriteFile(target, []byte(oldContents), 0o600); err != nil {
		t.Fatalf("write existing private file: %v", err)
	}
	verifyErr := errors.New("unsafe inherited ACL")
	err := atomicWritePrivateFileWithVerifier(target, []byte(newContents), 0o600, 0o700, func(tmpPath string) error {
		data, readErr := os.ReadFile(tmpPath)
		if readErr != nil {
			t.Fatalf("read empty temporary file: %v", readErr)
		}
		if len(data) != 0 {
			t.Fatalf("verifier saw %q, want an empty temporary file", data)
		}
		return verifyErr
	})
	if !errors.Is(err, verifyErr) {
		t.Errorf("AtomicWritePrivateFile() error = %v, want verifier refusal", err)
	}
	if err != nil && strings.Contains(err.Error(), newContents) {
		t.Fatalf("refusal leaked private file contents: %v", err)
	}
	data, readErr := os.ReadFile(target)
	if readErr != nil {
		t.Fatalf("read preserved private file: %v", readErr)
	}
	if string(data) != oldContents {
		t.Fatalf("private file = %q, want preserved contents %q", data, oldContents)
	}
	matches, globErr := filepath.Glob(filepath.Join(dir, ".credentials.toml.*.tmp"))
	if globErr != nil {
		t.Fatalf("glob temporary files: %v", globErr)
	}
	if len(matches) != 0 {
		t.Fatalf("temporary private files remain: %v", matches)
	}
}
